### PR TITLE
CI: Use separate scheduled pipeline for Flutter beta builds

### PR DESCRIPTION
**Pull request by kuhnroyal**
Simple approach but should be enough for now.
Hope the caching works with `2.5.x`.
This should also speed up the single steps by a lot.

### CODE REVIEW

**Comment by m0nac0** [comment]
@kuhnroyal Just to make sure, you intended this to still be a draft, right?

**Comment by kuhnroyal** [comment]
This is just an idea, if you think this is a possible solution for now then I can mark it ready.
It would be interesting to see if the check times improve after repeated usage of the same fixed version.

Maybe you can re-run the check a couple times.

**Comment by m0nac0** [comment]
Ah, I see. I get the split between stable flutter for PRs and beta flutter on a cron job. But I don't understand why this would improve run times. What is being cached?
I remember setting up caching for flutter in Github Actions in the past, but that involved using the cache action.

**Comment by kuhnroyal** [comment]
Well the hope is for `2.5.x` but I think we probably need to pin it directly. Then the Flutter SDK should be cached automatically.

**Comment by m0nac0** [comment]
Ah interesting, was the flutter action updated to support this? I thought it wasn't supported because https://github.com/subosito/flutter-action/issues/16 is still open...

**Comment by kuhnroyal** [comment]
I see, I mostly use private runners which behave differently here. So this might not work at all :(

Still think we should run the main CI flow on stable and have a cron trigger for beta.
Not sure if it is worth to combine steps to save 50s build time which is run in parallel anyways.
You also lose the direct feedback on what failed and have to look int the logs of the steps instead.

**Comment by m0nac0** [comment]
Yeah I agree about having these two separate CI workflows. I've added caching of flutter as a test. For macos this is a noticeable speedup in my experience, ubuntu remains to be seen.

The dilemma here was previously: in the cache-key you need to specify the flutter version, otherwise you could never update flutter, because the old flutter version would always be restored from cache. But there is no (easy) API for retrieving the latest flutter version on a channel. So if you wanted to just use a flutter channel (and not a specific version), you'd first need to always install flutter to find out the latest version. At that point, caching is useless.

If we pin the flutter version, this is not a problem, anymore.

**Comment by kuhnroyal** [comment]
Sounds good, should probably set it to `2.5.3` then.

**Pull request merged**
