### PR TITLE
Null safety (cherry-pick from upstream)

### LINKED ISSUE #16: Add null safety (NNBD) support
Looks like NNBD is available on flutter-mapbox-gl master.

### PR DESCRIPTION
**Pull request by m0nac0**
Fixes #16 

Switch to null safe (NNBD) mode, mostly cherry-picked and adapted from upstream (tobrun/flutter-mapbox-gl). Includes two more recent bug fixes from upstream that seem to be related.

### CODE REVIEW

**Comment by m0nac0** [comment]
I haven't found any regressions, feedback and results of your manual testing are very welcome!

**Comment by kuhnroyal** [comment]
This is huge, I had a couple things laying around but didn't find the time to push it further. I will see if i can test this tomorrow.

**Comment by kuhnroyal** [comment]
I am running into `fatal error: module 'Mapbox' not found` in https://github.com/m0nac0/maplibre-annotation-extension/blob/master/MapboxAnnotationExtension/Annotations/MGLStyleAnnotation.h
Any idea what I can change in my setup?

**Comment by m0nac0** [comment]
Are you compiling the example app?

**Comment by m0nac0** [comment]
And have you run `pod update`, as the CI does? If I remember correctly, that was how @mindthefish solved this issue in #9.

**Comment by kuhnroyal** [comment]
Will, I am trying to use it in my app which is now possible due to the NNBD migration.
I am trying to mirror the example and added both pods to my Podfile, like in the example.
I also ran `pod update` which downloaded the git repos.

**Comment by m0nac0** [comment]
Are you also running `pod update` in the same folder as the CI? I unfortunately don't know that much about iOS development, but the error is exactly the same I was seeing before #9 was merged.

**Comment by kuhnroyal** [comment]
Hmm somehow the Mapbox framework is still in there, don't think this is something that we want.

**Comment by kuhnroyal** [comment]
Ok, I am starting to understand this a little better. Managed to get it to work on this branch. Looking good so far.

**Comment by m0nac0** [comment]
May I ask what you did to solve this?

A wild guess: could this file https://github.com/m0nac0/maplibre-annotation-extension/blob/master/Podfile.lock be the reason the Mapbox SDK is/was wrongfully loaded?

**Comment by kuhnroyal** [comment]
There are 2 things that were confusing to me.
1. The xcframework in MapLibre-native is still called `Mapbox` in 5.12.1 (I didn't see this before) - that is why the name change was reverted in https://github.com/m0nac0/maplibre-annotation-extension/commit/0a24c3a62eac2d7cca181dd40526757a17ca4eed
2. Due to the Git dependency in the `Podfile` you always need to run `pod update` AND afterwards `pod install` or it won't work

And yes I am wondering the same, not sure if the `Podfile.lock` should even be committed there.

**Comment by mindthefish** [comment]
> There are 2 things that were confusing to me.
> 
> 1. The xcframework in MapLibre-native is still called `Mapbox` in 5.12.1 (I didn't see this before) - that is why the name change was reverted in [m0nac0/maplibre-annotation-extension@0a24c3a](https://github.com/m0nac0/maplibre-annotation-extension/commit/0a24c3a62eac2d7cca181dd40526757a17ca4eed)
> 2. Due to the Git dependency in the `Podfile` you always need to run `pod update` AND afterwards `pod install` or it won't work
> 
> And yes I am wondering the same, not sure if the `Podfile.lock` should even be committed there.

Yes, `pod install` has to be executed after `pod update`, although the output says it is running `pod install` after update automatically.
Regarding the `Podfile.lock`: Is it best practice to leave it out of the repository?

**Comment by kuhnroyal** [comment]
Hmm I don't think it matters, the `Podfile` should only be used for the example app in that repo. We are only interest in the `.podspec` when using it as dependency.

**Comment by mindthefish** [comment]
I was able to run the examples of that branch on an iPad Pro running iOS 14.7.1 and will test on 15.0.2 on Monday. Not done with the review though.

**Comment by mindthefish** [comment]
Able to compile and run on iPadOS 15.0.2. Crashes when I want to download offline maps.

```
Region download progress 0.0
libc++abi: terminating with uncaught exception of type std::__1::regex_error
* thread #27, name = 'com.mapbox.mbgl.DatabaseFileSource', stop reason = signal SIGABRT
    frame #0: 0x00000001bb8e79c4 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bb8e79c4 <+8>:  b.lo   0x1bb8e79e4               ; <+40>
    0x1bb8e79c8 <+12>: pacibsp
    0x1bb8e79cc <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1bb8e79d0 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
Exited (sigterm)
```

**Comment by m0nac0** [comment]
@mindthefish Have you checked whether that crash also happens before this PR?

**Comment by mindthefish** [comment]
Just tested, yes, it also happens on [`main`](https://github.com/m0nac0/flutter-maplibre-gl/tree/main). It is not caused by this PR.

**Comment by m0nac0** [comment]
Thank you for testing, would you mind opening a separate issue for the crash then?

**Comment by m0nac0** [comment]
Would anyone like to give more feedback on this? Otherwise I'd merge this.

**Pull request merged**
